name: Deploy Application

on:
  workflow_run:
    workflows: [Code Quality Check, Postman API Tests]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3
      #
      # - name: Set up Python
      #   uses: actions/setup-python@v3
      #   with:
      #     python-version: '3.12'

      - name: Deploy to Production
        run: |
          echo "Deploying the application to production server"
          # Your deployment logic here, for example:
          # ssh user@your-server "cd /path/to/app && git pull && systemctl restart your-app.service"
          
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'



