name: Postman API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  paths:
    - app.py
    - auto_test_postman_collection.json

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # or the version you prefer

    - name: Install Newman
      run: npm install -g newman

    - name: Start FastAPI server
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        uvicorn app:app --host 0.0.0.0 --port 8000 &

    - name: Run Postman tests
      run: |
        newman run auto_test_postman_collection.json --reporters cli

