name: Code Quality Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        source venv/bin/activate
        pip install -r requirements.txt
        pip install ruff autopep8

    - name: Run Ruff linting
      run: |
        source venv/bin/activate
        ruff check --output-format github .

    - name: Run autopep8 for code formatting
      run: |
        source venv/bin/activate
        autopep8 --diff .
